backend:
  name: test-repo

media_folder: static/uploads
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: "content/pages"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
