backend:
  name: test-repo
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/uploads
public_folder: uploads

collections:
  - name: api
    label: api
    folder: "content/pages/api"
