backend:
  name: test-repo
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/uploads
public_folder: uploads

collections:
  - name: api
    label: api
    folder: "content/pages/api/"
    fields:
      - { label: "Path", name: "path", widget: "hidden", default: "" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
